theme = "rose_pine"

[editor]
line-number = "absolute"
true-color = true
rulers = [ 80, 120 ]
color-modes = true

[editor.lsp]
enable = true
display-messages = true

[editor.file-picker]
hidden = false

